---
version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    ports:
      - "9200:9200"
    networks:
      - elastic
    environment:
      - discovery.type=single-node
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 120s
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  elastic:
